# Generated by Django 4.1.7 on 2023-03-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=10)),
                ('heading_to', models.CharField(blank=True, max_length=100, null=True)),
                ('arrival_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.TimeField()),
            ],
            options={
                'db_table': 'times',
                'managed': False,
            },
        ),
    ]
