# Generated by Django 4.1.5 on 2023-02-02 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stationinfo',
            options={},
        ),
    ]
