# Generated by Django 4.2.1 on 2023-05-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stations',
            name='updnLine',
            field=models.CharField(default='up', max_length=2),
            preserve_default=False,
        ),
    ]
