# Generated by Django 4.1.7 on 2023-03-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stations',
            options={'managed': False, 'verbose_name': 'Stations'},
        ),
        migrations.AlterModelOptions(
            name='times',
            options={'managed': False, 'verbose_name': 'Times'},
        ),
    ]
