# Generated by Django 4.1.7 on 2023-03-10 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_alter_stations_options_alter_times_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stations',
            options={'managed': False, 'verbose_name': 'Stations', 'verbose_name_plural': 'Stations'},
        ),
        migrations.AlterModelOptions(
            name='times',
            options={'managed': False, 'verbose_name': 'Times', 'verbose_name_plural': 'Times'},
        ),
    ]
