# Generated by Django 4.1.5 on 2023-02-02 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_alter_stationinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stationinfo',
            options={'managed': True},
        ),
    ]
