# Generated by Django 4.1.7 on 2023-03-12 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_alter_stations_options_alter_times_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stations',
            options={'verbose_name': 'Stations', 'verbose_name_plural': 'Stations'},
        ),
        migrations.AlterModelOptions(
            name='times',
            options={'verbose_name': 'Times', 'verbose_name_plural': 'Times'},
        ),
    ]
